sudo: required
services:
  - docker

before_install:
  - docker build -t thepratyush/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thepratyush/react-test npm test -- --coverage

after_success:
  - docker build -t thepratyush/multi-client ./client
  - docker build -t thepratyush/multi-nginx ./nginx
  - docker build -t thepratyush/multi-server ./server
  - docker build -t thepratyush/multi-worker ./worker
  #log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push thepratyush/multi-client
  - docker push thepratyush/multi-nginx
  - docker push thepratyush/multi-server
  - docker push thepratyush/multi-worker